---
title: "Q2 - 886 Ass 1"
author: "Zexuan Fang"
date: "22/08/2019"
output: pdf_document
---
Q2 (a)
```{r, echo=FALSE}
Scott_loan_amount <- 600000
Scott_loan_term_1 <- 30
Scott_offset_balance <- 100000
Scott_interestRate <- 0.035
Scott_offset_contribution <- Scott_offset_balance*Scott_interestRate
Scott_repayment_no_offset <- Bill_repayment
Scott_repayment_no_offset
```



(b) - i
```{r, echo=FALSE}
instalment <- rep(Scott_repayment_no_offset, 30)
offset_interest_earned <- rep(Scott_offset_contribution, 30) ## vector of interest earned from offset account
interest_repayment <- rep(NA, 30) ## current year interest repayment for mortgage
principal_repayment <- rep(NA,30) ## current year principal repayment for mortgage
outstanding_loan_BoY <- rep(NA, 30) ## loan outstanding begining of the year 
outstanding_loan_BoY[1] <- Scott_loan_amount 


interest_repayment[1] <- outstanding_loan_BoY[1] * Scott_interestRate


principal_repayment[1] <- instalment[1] + offset_interest_earned[1] - interest_repayment[1]

outstanding_loan_EoY <- rep(NA, 30) ## loan outstanding end of the year 
outstanding_loan_EoY[1] <- 
  outstanding_loan_BoY[1] - principal_repayment[1]

for (i in 2:30) {
  outstanding_loan_BoY[i] <- outstanding_loan_EoY[i-1]
  
  interest_repayment[i] <- outstanding_loan_BoY[i]* Scott_interestRate
  
  principal_repayment[i] <- instalment[i] + offset_interest_earned[i] - interest_repayment[i]
   
  outstanding_loan_EoY[i] <- outstanding_loan_BoY[i] - principal_repayment[i]
}



Scott_repayment_schedule_30year <- data.frame(outstanding_loan_BoY,
                                              instalment, offset_interest_earned, interest_repayment, 
                                              principal_repayment, outstanding_loan_EoY) ## the 30-year repayment schedule

colnames(Scott_repayment_schedule_30year) <- c("BoY", 
                                                "Instalment", "Benefit",
                                               "Interest Repay", 
                                               "Principal Repay", "EoY")

Scott_repayment_schedule_30year
```





(b)-ii
```{r, echo=FALSE}
Scott_repayment_schedule_short <- Scott_repayment_schedule_30year[1:23,] ## the 23-year repayment schedule 

## adjusting the final instalment amount at year 23, by summing loan outstanding BoY and the current year interest repayment and deducting the $100000 offset balance and the $3500 interest earned on offset.
Scott_repayment_schedule_short$`Instalment`[23] <- 
  Scott_repayment_schedule_short$`BoY`[23] +
  Scott_repayment_schedule_short$`Interest Repay`[23]-
  Scott_offset_balance -
  Scott_repayment_schedule_short$`Benefit`[23]

## adjusting the principal repayment current year at year 23, by differencing between the current year instalment and the interest repayment. 
Scott_repayment_schedule_short$`Principal Repay`[23] <-
  Scott_repayment_schedule_short$`Instalment`[23] -
  Scott_repayment_schedule_short$`Interest Repay`[23]

## adjusting the loan outstanding EoY at year 23
Scott_repayment_schedule_short$`EoY`[23] <-
  Scott_repayment_schedule_short$`BoY`[23] -
  Scott_repayment_schedule_short$Benefit[23]-
  Scott_repayment_schedule_short$`Principal Repay`[23] -
  Scott_offset_balance 

Scott_repayment_schedule_short
```